meta:
  environment: barricade-warden

  stemcell:
    name: bosh-warden-boshlite-ubuntu
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: barricade_z1
    instances: 1
    persistent_disk: 4096

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

networks:
- name: barricade1
  type: manual
  subnets:
  - range: 10.244.8.0/24
    name: barricade1
    gateway: 10.244.8.1
    static:
      - 10.244.8.2-10.244.8.60
