meta:
  environment: (( params "please set meta environment" ))
  dns_root: (( params "please set meta dns_root" ))
  security_groups: (( params "please set meta security_groups" ))
  persistent_disk: 4096

  stemcell:
    name: bosh-aws-xen-ubuntu
    version: latest

jobs:
  - name: barricade_z1
    instances: 1
    persistent_disk: (( grab meta.persistent_disk ))

compilation:
  cloud_properties:
    instance_type: m1.small

resource_pools:
  - name: small_z1
    cloud_properties:
      instance_type: m1.small

networks:
  - name: floating
    type: vip
    cloud_properties: {}
  - name: barricade1
    type: dynamic
    cloud_properties:
      security_groups: (( grab meta.security_groups ))
