meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: barricade_z1
    templates:
    - name: barricade
      release: barricade
    instances: 1
    resource_pool: small_z1
    networks:
      - name: barricade1
        static_ips: (( static_ips(0) ))
    properties:
      barricade:
        key: (( grab meta.barricade.key ))

networks: (( params "please set networks" ))

properties: {}
